### PR TITLE
V2 API break migrations

### PR DESCRIPTION
**Pull request by alainbryden**
Once V2 drops, this branch will have to be merged to main. Can't be merged early because some APIs are backwards-and-forwards-incompatible from 1.7 to 2.0

### CODE REVIEW

**Comment by stedel** [comment]
(ping) V2 is live now: https://store.steampowered.com/news/app/1812820/view/3376031059787349060

**Comment by azzarello** [comment]
So I pulled down this branch, but there still seems to be a few issues (much less than running the main branch version though):
```
RUNTIME ERROR
analyze-hack.js@home (PID - 27)
Args: ["--all", "--silent"]

Cannot read properties of undefined (reading 'hostname')
stack:
TypeError: Cannot read properties of undefined (reading 'hostname')
at Module.main (home/analyze-hack.js:143:60)
at executeJSScript (file:///home/cd/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:119329)
```
and 
```
daemon.js: WARNING: daemon.js Caught an error in the targeting loop: Cannot read properties of undefined (reading 'timeToHack')
TypeError: Cannot read properties of undefined (reading 'timeToHack')
    at doTargetingLoop (home/daemon.js:692:60)
    at async Module.main (home/daemon.js:336:5)
```
I don't have a huge amount of JS experience and this repo is rather massive, but I can take a look at making a pull request if I could get some hints/suggestions.

**Comment by realacesu** [comment]
`stockmaster.js` is unsuccessful in determining if the player has market access on this branch.
```stockmaster.js: SUCCESS: Purchased 4SMarketDataTixApi for $27.602b (At 8h 12m 41s into BitNode)

stockmaster.js: SUCCESS: Purchased 4SMarketData for $1.104b (At 8h 12m 42s into BitNode)```
is being spammed

**Comment by alainbryden** [comment]
Yeah this branch is nowhere near done, and I'm on vacation for the next week away from my computer, so you might want to rake a break from the game for a bit.

**Comment by azzarello** [comment]
> Yeah this branch is nowhere near done, and I'm on vacation for the next week away from my computer, so you might want to rake a break from the game for a bit.

Sounds good. I will do my best to contribute some fixes during that time. Is it okay with you if we leave this thread to discuss changes, or should I open an issue?

**Comment by alainbryden** [comment]
Here is fine, there's also an issue open.

**Comment by eyoung100** [comment]
For those of you who still want to play, assuming you have Steam, Right Click BitBurner ==> Properties ==> Betas ==> Set the branch to 1.7.0 until  [alainbryden](https://github.com/alainbryden) can get the API rewrite done.  I'd help but work has me so busy, with no free time

**Comment by laisier** [comment]
> For those of you who still want to play, assuming you have Steam, Right Click BitBurner ==> Properties ==> Betas ==> Set the branch to 1.7.0 until [alainbryden](https://github.com/alainbryden) can get the API rewrite done. I'd help but work has me so busy, with no free time

I did this and I keep getting this error


RUNTIME ERROR
/Tasks/contractor.js@home (PID - 1944)


ns.read('/Temp/contract-types.txt') returned a bad result: "ERROR: Cannot read properties of undefined (reading 'name')".
Script: /Temp/contract-types.txt.js
Args: ["[{\"contract\":\"contract-338482-Bachman&Associates.cct\",\"hostname\":\"summit-uni\"},{\"contract\":\"contract-490816.cct\",\"hostname\":\"rothman-uni\"},{\"contract\":\"contract-403659-TianDiHui.cct\",\"hostname\":\"global-pharm\"},{\"contract\":\"contract-10840-Bachman&Associates.cct\",\"hostname\":\"computek\"},{\"contract\":\"contract-85510-TheSyndicate.cct\",\"hostname\":\"catalyst\"},{\"contract\":\"contract-116170.cct\",\"hostname\":\"run4theh111z\"},{\"contract\":\"contract-917085.cct\",\"hostname\":\"run4theh111z\"},{\"contract\":\"contract-174789-Bachman&Associates.cct\",\"hostname\":\"powerhouse-fitness\"},{\"contract\":\"contract-891905-Bachman&Associates.cct\",\"hostname\":\"univ-energy\"},{\"contract\":\"contract-284449-Bachman&Associates.cct\",\"hostname\":\"zb-institute\"},{\"contract\":\"contract-879230.cct\",\"hostname\":\"zb-institute\"},{\"contract\":\"contract-313050.cct\",\"hostname\":\"microdyne\"},{\"contract\":\"contract-424910-Bachman&Associates.cct\",\"hostname\":\".\"},{\"contract\":\"contract-934847-NiteSec.cct\",\"hostname\":\".\"},{\"contract\":\"contract-933477.cct\",\"hostname\":\"applied-energetics\"},{\"contract\":\"contract-275412-Netburners.cct\",\"hostname\":\"foodnstuff\"}]"]
Command: Object.fromEntries(JSON.parse(ns.args[0]).map(c => [c.contract, ns.codingcontract.getContractType(c.contract, c.hostname)]))
The script was likely passed invalid arguments. Please post a screenshot of this error on discord.
stack:
Error:
ns.read('/Temp/contract-types.txt') returned a bad result: "ERROR: Cannot read properties of undefined (reading 'name')".
Script: /Temp/contract-types.txt.js
Args: ["[{\"contract\":\"contract-338482-Bachman&Associates.cct\",\"hostname\":\"summit-uni\"},{\"contract\":\"contract-490816.cct\",\"hostname\":\"rothman-uni\"},{\"contract\":\"contract-403659-TianDiHui.cct\",\"hostname\":\"global-pharm\"},{\"contract\":\"contract-10840-Bachman&Associates.cct\",\"hostname\":\"computek\"},{\"contract\":\"contract-85510-TheSyndicate.cct\",\"hostname\":\"catalyst\"},{\"contract\":\"contract-116170.cct\",\"hostname\":\"run4theh111z\"},{\"contract\":\"contract-917085.cct\",\"hostname\":\"run4theh111z\"},{\"contract\":\"contract-174789-Bachman&Associates.cct\",\"hostname\":\"powerhouse-fitness\"},{\"contract\":\"contract-891905-Bachman&Associates.cct\",\"hostname\":\"univ-energy\"},{\"contract\":\"contract-284449-Bachman&Associates.cct\",\"hostname\":\"zb-institute\"},{\"contract\":\"contract-879230.cct\",\"hostname\":\"zb-institute\"},{\"contract\":\"contract-313050.cct\",\"hostname\":\"microdyne\"},{\"contract\":\"contract-424910-Bachman&Associates.cct\",\"hostname\":\".\"},{\"contract\":\"contract-934847-NiteSec.cct\",\"hostname\":\".\"},{\"contract\":\"contract-933477.cct\",\"hostname\":\"applied-energetics\"},{\"contract\":\"contract-275412-Netburners.cct\",\"hostname\":\"foodnstuff\"}]"]
Command: Object.fromEntries(JSON.parse(ns.args[0]).map(c => [c.contract, ns.codingcontract.getContractType(c.contract, c.hostname)]))
The script was likely passed invalid arguments. Please post a screenshot of this error on discord.
at autoRetry (home/helpers.js:306:52)
at async getNsDataThroughFile_Custom (home/helpers.js:172:22)
at async getNsDataThroughFile (home/helpers.js:137:12)
at async contractsDictCommand (home//Tasks/contractor.js:20:61)
at async Module.main (home//Tasks/contractor.js:22:29)

**Comment by storm-taco** [comment]
> > For those of you who still want to play, assuming you have Steam, Right Click BitBurner ==> Properties ==> Betas ==> Set the branch to 1.7.0 until [alainbryden](https://github.com/alainbryden) can get the API rewrite done. I'd help but work has me so busy, with no free time
> 
> I did this and I keep getting this error
> 
> RUNTIME ERROR /Tasks/contractor.js@home (PID - 1944)
> 

If you already ran as v2, you'll have v2 data in your temp files.
run cleanup.js
then restart.
Fixed for me.

**Comment by alainbryden** [comment]
Just going to merge what I've got so far to cut down on the number of questions / comments / contributions on things I've already migrated

**Comment by storyd** [comment]
> Also wanted to add another bug I found in `work-for-factions.js` I wanted to share:
> 
> ```
> WARNING: work-for-factions.js caught an unhandled error in its main loop. Trying again in 5 seconds...
> The faction "Netburners" does not support any of the known work types. Cannot work for this faction!
> ```

This is originating from https://github.com/alainbryden/bitburner-scripts/blob/ccfef3207bbb46de21ec42369093b867093c23b8/work-for-factions.js#L837 

workRepGainRate has been removed.

In addition  the following lines also reference removed player attributes.

### workRepGained
https://github.com/alainbryden/bitburner-scripts/blob/ccfef3207bbb46de21ec42369093b867093c23b8/work-for-factions.js#L749

### workRepGainRate
https://github.com/alainbryden/bitburner-scripts/blob/ccfef3207bbb46de21ec42369093b867093c23b8/work-for-factions.js#L776-L778
https://github.com/alainbryden/bitburner-scripts/blob/ccfef3207bbb46de21ec42369093b867093c23b8/work-for-factions.js#L992-L994

### className
https://github.com/alainbryden/bitburner-scripts/blob/ccfef3207bbb46de21ec42369093b867093c23b8/work-for-factions.js#L622

#### Notes
I haven't found a direct replacement for `workRepGainRate`. Due to the comment in the 2.0 migration that `All work type give their reward immediately.` we might be able to shim the rate query by double polling but that is not optimal.

**Comment by alainbryden** [comment]
@storyd no need to shim. I already have a bit of logic in work for factions that measure the change in rep every status update (30 seconds) to improve the accuracy of the game's reported repgainrate.

We can switch to just using the measured value and toss the code that gets it from the game api first. The other statements used in boolean conditions can probably be collapsed permanently to their true/false result based on the new behaviour.

**Comment by storyd** [comment]
found another bug due to Player attributes.

https://github.com/alainbryden/bitburner-scripts/blob/557d6ec701dfc15aec9614331994748e92abd75b/helpers.js#L421

`player` evaluates true so `await .. ns.stock.hasTIXAPIAccess()` is never evaluated. `player` param is no longer needed for this statement nor function scope.

Expected statement
```
if (!(await getNsDataThroughFile(ns, 'ns.stock.hasTIXAPIAccess()', '/Temp/hasTIX.txt'))) return 0;
```

Do you want me to continue to document here, start making a list and/or prs, or a new ticket per issue found?

**Comment by alainbryden** [comment]
@storyd Appreciate all the effort. I tackled a few yesterday, and will tackle a few more this morning. Once the dust settles, if you create a new issue per outstanding bug found, that would be great. Some issues are easier to fix than others, so separate tickets makes it easier to check off the majority of easy once quickly, then chip away at the more difficult ones later.

Also, feel free to submit a PR for any obvious ones with a straightforward solution (like properties moved to namespaces)

**Comment by alainbryden** [comment]
I'm going to start putting a rocket emoji on the issues identified here that I think are now addressed.

**Comment by storyd** [comment]
> I'm going to start putting a rocket emoji on the issues identified here that I think are now addressed.

however you want to handle it, but for sanity you might want to try 
image

**Pull request merged**
