### PR TITLE
update the status output

### PR DESCRIPTION
**Pull request by Mendenj85**
Changed 'Profit' to 'Total Profit', also removed totalProfit from the Net calc as, imo at least, the Net should only be the net gain or loss from what you're currently holding, and not include the already gained profits, especially since you had a profit line already (hereby changed to Total Profit)

Edit - thinking about it more, I would change the net to either Unrealized Gains or Unrealized Profit, could even change Total Profit to Realized Gains :)

### CODE REVIEW

**Comment by Mendenj85** [comment]
Not 100% if the total profit line will keep adding, or only add what's just been sold, that might need to be looked at more, --commenting as i'm watching my script tail

**Comment by Mendenj85** [comment]
Actually, looking at this more, with what I was looking for think I mixed up the way you have it worded with how I would've, might as well just deny this one, lol, apologize for the time waste, lol

**Comment by Mendenj85** [comment]
Thinking about it more, I would change Net to Unrealized Gain

**Comment by alainbryden** [comment]
Hey sorry for the confusion. At this point, too many people are used to the current output to change it, but you're right - I was originally not very specific with my terms because I was trying to keep the message from wrapping at the old default window width. Probably doesn't even make a difference now.

**Pull request closed without merging**
