### PR TITLE
Add logging of ETAs for achieving Rep requirements

### PR DESCRIPTION
**Pull request by ShawnPatton**
I'm tempted to make a helper function that you can feed multiple requirements, and it would auto grab all the rates and pick the longest duration before spitting out the ETA string. But for now, this is what we've got.

### CODE REVIEW

**Review by alainbryden — CHANGES_REQUESTED** [review]
Will approve, but first we should tweak the ETA when working for a corporation, because we're not working for a full 8 hours, we need to reduce the rep gain rate by a factor representing the current penalty for cancelling early.

**Comment by ShawnPatton** [comment]
Just realized that the penalty isn't always a half. Will correct tonight.

**Comment by ShawnPatton** [comment]
Alright, this was a tricky problem to solve. Wound up using a more appropriate name for the existing temp file that the backdoor tool creates, and made it also create the file we need.

**Comment by ShawnPatton** [comment]
After a lot of debug messages, I finally figured out why it sometimes would skip all status updates until new work was chosen.

**Review by alainbryden — COMMENTED** [review]
Excellent effort, but before merging I'm going to make a couple of tweaks.

To date, I'm pretty sure I don't have any scripts that implicitly rely on a temp file being generated by some other script, and I would prefer to keep it that way. I do appreciate the effort here to minimized the amount of work being done on the status update, my preference would be to add the logic for getting the list of servers and their backdoor status directly to `workForMegacorpFactionInvite` itself (without increasing RAM cost of course).

Besides that and a couple of tabs -> whitespace, I like your changes and will aim to have them merged soon! Thanks for the contribution.

**Comment by alainbryden** [comment]
I'm working on a commit that will introduce these changes in a slightly different way, but something that surprising me is that I seem to be gaining REP at twice the predicted rate:

So every 2 minutes (by default) there's a status update, but the time has gone down by 4 minutes.
image

Are you seeing this too, or did I mess up something when updating your work? The math seems right, so I can't figure out why this would be. I'm even starting to think it might be a bug in the game granting more REP than it should...

**Comment by alainbryden** [comment]
Alright, I've included your changes with some tweaks to minimize new code, dependency on backdooring script, and minor code-style preferences. Hope it's good with you, and thanks!

**Comment by ShawnPatton** [comment]
Unfortunately, I don't see where the doubled Rep gain is coming from. I know that the faction part doesn't do that on my branch. Not sure if I thoroughly double-checked the change-in-ETA for company work in my branch, though that's not where your issue lies.

**Comment by alainbryden** [comment]
image

You know what, I tried this on my steam gameplay, where I recently restarted, and I saw the opposite, I was earning rep about 75% as fast as I should be:
image

So I'm really thinking this is something to do with the game, maybe some hidden bitnode multipliers or similar that aren't getting surfaced in the "workRepGain" value?

**Pull request closed without merging**
