### PR TITLE
Installer

### PR DESCRIPTION
**Pull request by raziel420**
Adds in working installer and framework for player owned server management.  Purchasing and upgrading work already but daemon does not like it and throws errors about targeting.

### CODE REVIEW

**Comment by raziel420** [comment]
Oh the framework for playerservers is commented out of daemon around line 220 with the rest of the run once applications

**Comment by archraziel** [comment]
host-manager.js already buys servers. I don't think we need the playerserver.ns

**Comment by alainbryden** [comment]
Rather than maintain a near-copy of "git-pull", I do want to support a flag on the former that pulls all files from the remote repository, but I need to do a little research and find a way to get a list of all files in a git repository, so that they don't have to be maintained as a manual liste (prone to human error), and so that it works on peoples' own repositories. Hope that makes sense.

**Comment by alainbryden** [comment]
All the above said, definitely keep your own fork and keep making changes! I'm glad I helped you get started, but everyone likes to play the game a bit differently and eventually ends up with their own unique set of scripts. Looks like you're well on your way - hope you enjoy :)

**Comment by alainbryden** [comment]
All set now - git pull will automatically get all files in the target
repository by default - no need to hard-code anything. I'll add a blurb to
the readme.

**Pull request closed without merging**
