### PR TITLE
Adjust tail window size and position

### PR DESCRIPTION
**Pull request by rraumberger**
Hi. I noticed issue #394 and it somewhat bothered me too, so I created this small PR to make some adjustments to the default tail window size and placement.

This algorithm is not very sophisticated and can still produce overlaps in window placement, but it works good enough for me.

I also tried a different version which directly uses the window api and is slightly more dynamic and resilient, but I don't think it justifies blowing up the ram cost of the helper script to 26GB due to accessing `document`.

Since the result of this algorithm is a matter of personal taste, feel free to adjust the values to your liking.

image

### CODE REVIEW

**Review by alainbryden — APPROVED** [review]
You're a rockstar.

We can use eval("document") to get a "free" document (I do this in casino.js and stats.js) but this is a great start.

**Comment by alainbryden** [comment]
Made a little tweak to your logic to simply keep a running counter and "cascade" tail windows as they are opened. Uses mod like you did to wrap them after a certain number.
image

**Comment by rraumberger** [comment]
> You're a rockstar.
> 
> We can use eval("document") to get a "free" document (I do this in casino.js and stats.js) but this is a great start.

Ohh.. Didn't know about the `eval` trick. Today I learned :)

**Comment by rraumberger** [comment]
> Made a little tweak to your logic to simply keep a running counter and "cascade" tail windows as they are opened. Uses mod like you did to wrap them after a certain number.

That's awesome. I kinda overestimated Bitburners capabilities here and thought global shared variables wouldn't work due to being called from a different script.

**Comment by alainbryden** [comment]
It's a blessing and a curse :)

**Pull request merged**
