### PR TITLE
Removed Sleeve .location check

### PR DESCRIPTION
**Pull request by xtrapwr**
For now commented out the %  check as it relied on the .location field returned from ns.sleeve.getTasks(), and that is no longer in the return with v2

### CODE REVIEW

**Comment by xtrapwr** [comment]
This should fix #209

**Comment by alainbryden** [comment]
Is there any other way to get this sleeve chance info? Without it, sleeves will early on be assigned to tasks they fail and build up a ton of shock, making them useless for the rest of the augmentation.

**Comment by xtrapwr** [comment]
Running with my garbage sleeves, they don't appear to be failing ANY bladeburner tasks. I also can't seem to find any available sleeve property that shows a percentage success when doing BB stuff. I think the blade burner sleeve interactions have changed, but I'm still looking through the diff files around sleeves

**Comment by xtrapwr** [comment]
Nevermind, they are just quietly failing. Retract the request as I further troubleshoot.

**Comment by xtrapwr** [comment]
After further testing all available get methods in sleeve v2, and running BB assignments while monitoring fail/success messages in BB versus sync levels, it appears sleeves no longer lose sync on bb fails, though I have been unable to get a sleeve to fail any task other than recruitment. Until proven otherwise, I have removed the failure check completely.  You can hold this PR until we get additional support.

**Pull request closed without merging**
