### PR TITLE
Add infiltration automation service

### PR DESCRIPTION
**Pull request by trambelus**

### CODE REVIEW

**Comment by Evanito** [comment]
Requires you run a python program on your actual computer? https://pastebin.com/psmzQDEZ

**Comment by alendaris** [comment]
This looks like this is using an external tool, which I don't think is going to be supported in this repository. See #77.

**Comment by zocke1r** [comment]
the reward info text doesn't appear to be working properly only displaying NaN, NaN rep (31)

**Comment by trambelus** [comment]
> the reward info text doesn't appear to be working properly only displaying NaN, NaN rep (31)

Does anything show up in the debug console when you launch the infiltrator? And do you have BN5 unlocked?

**Comment by zocke1r** [comment]
> > the reward info text doesn't appear to be working properly only displaying NaN, NaN rep (31)
> 
> Does anything show up in the debug console when you launch the infiltrator? And do you have BN5 unlocked?

Nothing shows up in the debug console and i dont have BN5 unlocked yet

**Comment by zocke1r** [comment]
figured out the cause the `bnMults?.InfiltrationMoney ?? 1` in the formula to calc repGain and moneyGain needs to be in parentheses otherwise it returns NaN for some reason so` (bnMults?.InfiltrationMoney ?? 1)` works

**Comment by trambelus** [comment]
> figured out the cause the `bnMults?.InfiltrationMoney ?? 1` in the formula to calc repGain and moneyGain needs to be in parentheses otherwise it returns NaN as the ?? is only evaluate at the end of the calculation otherwise so` (bnMults?.InfiltrationMoney ?? 1)` works

Good catch. Pushed the fix.

**Comment by alainbryden** [comment]
I was going to start looking at integrating this into the repo now that infiltration has been tied to a new faction, but it looks like recent UI changes have broken its ability to find the buttons it needs (both the service and the looper)

**Review by alainbryden — CHANGES_REQUESTED** [review]
Blocked on adapting to the new ui

**Comment by abarnert** [comment]
I found a near-working (no websockets needed) script on ullbergm's fork, fixed it up, added a driver script, and created PR #173 for it. I'll look over the looper here to see if it does clever things I didn't think of (since it probably does) once I get a chance later.

**Comment by alainbryden** [comment]
Closing this rather stale take in favour of more recent PRs

**Pull request closed without merging**
