### PR TITLE
Numerous stock and player call changes

### PR DESCRIPTION
**Pull request by xtrapwr**
Tried to minimize RAM increase through getNsDataThroughFile calls and use of existing variables where able.

If this is too many at once let me know, trying to find balance between too many and too few changes per pull.

### CODE REVIEW

**Comment by alainbryden** [comment]
Good changes, but pretty far behind. Do a `git rebase origin/main` and resolve any conflicts

**Comment by xtrapwr** [comment]
I actually have no idea how to do that to a pull I can't auto merge. Let me rebase my main source and re-do the changes.

**Comment by alainbryden** [comment]
Whoa how did you merge this pr? I've obviously got my permissions set up wrong

**Comment by xtrapwr** [comment]
I have ... no idea. I only just fixed the re-base on my original branch.

**Pull request merged**
